name: (5.x) Run tests

# This workflow runs when any of the following occur:
# - On any changes

on:
  push:
    paths:
      - "src/**" # Match changes in source files.
      - "*.gradle" # Match changes in Gradle configuration.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-test-workflow:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Publish SAP and commons library to mavenLocal
        uses: ./.github/actions/5_local_maven_publisher
        with:
          version: ${{ steps.version.outputs.version }}
          revision: ${{ inputs.revision }}
          reference: ${{ inputs.reference }}

      - name: Run Gradle check
        run: ./gradlew check
